#!/bin/bash

HOME_DIR=$(readlink -f .)
mkdir -p $HOME_DIR/classes
rm -rf $HOME_DIR/classes/*.class

javac $HOME_DIR/src/*.java
mv $HOME_DIR/src/*.class $HOME_DIR/classes

export CLASSPATH=$CLASSPATH:$HOME_DIR/classes
