#!/bin/bash

. cs-common

append_classpath "CROWD_SAFE_MERGE_DIR"
append_classpath "CROWD_SAFE_COMMON_DIR"

#echo "classpath: $cp"

main_class="edu.uci.eecs.crowdsafe.analysis.merge.graph.GraphMergeSession"

java -cp $cp $main_class $1 $2 $3
  
