#!/bin/bash

. $csc/scripts/cs-common

function print_usage() {
  echo "Usage: cs-merge <left-run-dir> <right-run-dir>"
  echo "Usage: cs-merge -n <output-name> -o <output-dir> <left-run-dir> <right-run-dir>"
  echo "Usage: cs-merge -i <in-place-dir> <other-run-dir>"
  echo "\t[ -l <log-file-basename> (default \"merge.log\" ]"
  echo "\t-c <cluster-name>,... (include only these clusters)"
  echo "\t-x <cluster-name>,... (exclude these clusters)"
  echo "\t-d <crowd-safe-common-dir>"
  echo "\t-t (tag-based merge) (default)"
  echo "\t-u (unit clusters) (default)"
  echo "\tRun-dir must be preceded by c: (for cluster graph) or e: (for execution graph)"
  exit
}

check_help $1 print_usage

append_classpath "CROWD_SAFE_MERGE_DIR"
append_classpath "CROWD_SAFE_COMMON_DIR"

# echo "classpath: $cp"

main_class="edu.uci.eecs.crowdsafe.merge.graph.main.MergeTwoGraphs"

java -Xms512M -Xmx1536M -cp $cp $main_class $@
#java -cp $cp $main_class $@
  
