#!/bin/bash

. $csc/scripts/cs-common

function print_usage() {
  echo "Usage: cs-report -e <execution-dir>"
  echo "                 -d <dataset-dir>"
  echo "                 -f <report-file>"
  echo "                 -s <statistics-file>"
  echo "                 -a <alphas-file>"
  exit
}

check_help $1 print_usage

append_classpath "CROWD_SAFE_MERGE_DIR"
append_classpath "CROWD_SAFE_GRAPH_DIR"
append_classpath "CROWD_SAFE_COMMON_DIR"

# echo "classpath: $cp"

main_class="edu.uci.plrg.cfi.x86.merge.graph.main.ExecutionReporter"

java $vm_args -cp $cp $main_class $@
#java -cp $cp $main_class $@
  
